security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: $2y$12$IGO38ffi2bBHTVEdQyAPv.iwLiehXfROyHNC.Azz46LEWCr.cWPEy
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$lF.1xz4bfpZ33QDUZaFMvewO/fD/MI6tflPz9hCFe0dxe4WlIKBde
                        roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

            form_login:
                login_path: login
                check_path: login

#        secured_area:
#            # ...
#            logout:
#                path:   /logout
#                target: /

    access_control:
         - { path: ^/lucky/number, roles: ROLE_ADMIN }