security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        AppBundle\Entity\User:
                    algorithm: bcrypt
                    cost: 12

    providers:
         our_db_provider:
             entity:
                 class: AppBundle:User
                 property: username

#        in_memory:
#            memory:
#                users:
#                    ryan:
#                        password: $2y$12$IGO38ffi2bBHTVEdQyAPv.iwLiehXfROyHNC.Azz46LEWCr.cWPEy
#                        roles: 'ROLE_USER'
#                    admin:
#                        password: $2y$12$lF.1xz4bfpZ33QDUZaFMvewO/fD/MI6tflPz9hCFe0dxe4WlIKBde
#                        roles: 'ROLE_ADMIN'
    firewalls:
#        secured_area:
#            logout:
#                path:   /logout
#                target: /
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            http_basic: ~

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
    - { path: ^/lucky/number, roles: ROLE_ADMIN }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
