security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
         our_db_provider:
             entity:
                 class: App:User
                 property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            http_basic: ~
            form_login:
                login_path: login
                check_path: login
                username_parameter: form[_username]
                password_parameter: form[_password]
            logout:
                path:   /logout
                target: /login

    access_control:
         - { path: ^/lucky/number, roles: ROLE_ADMIN }