security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
         our_db_provider:
             entity:
                 class: App:User
                 property: username

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            http_basic: ~
            logout:
                  path:   /logout
                  target: /

            form_login:
                login_path: login
                check_path: login

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

    access_control:
         - { path: ^/lucky/number, roles: ROLE_ADMIN }