index:
    path: /
    controller: App\Controller\DefaultController::index

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\DefaultController::number

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout